#+title: Where are the smarts?

There is an old saw in AI research to the extent that when you know
how to solve a problem, it isn't AI anymore.[fn:: The earliest
reference found by Quote Investigator was from 1971: “AI is a
collective name for problems which we do not yet know how to solve
properly by computer,” which was attributed to Betram Raphael by
Donald Michie. [[https://quoteinvestigator.com/2024/06/20/not-ai/]]] AI
researchers are often slightly irritated by this kind of thing and
refer to it as “moving the goalposts:” some ability that was
previously thought to require “real” intelligence is no longer thought
to do so when it is actually achieved.  When the computer Deep Blue
beat chess grandmaster Gary Kasparov, there was, initially, a feeling
that AI was catching up to humans in intellection ability, but then,
later, we decided that perhaps being good at chess wasn't the same as
being smart.

Right now we are in the middle of a similar debate around LLMs.  Have
we -- this time -- achieved “real” intelligence, or will it all turn
out to be another specialist trick, useful in many circumstances but
not in all, and falling short of generalist intelligence?  On the one
hand, look at all the amazing things LLMs can do! Surely those things
require intelligence? On the other hand, sure, but that's what we say
every time, so somehow that argument cannot carry the force required.
On the third hand, /one/ day we are going to crack it and maybe that
day is this day?

I'd like to think about this problem by looking at what happened to
previous kinds of AI.  Why did we “move the goalposts” in the past?
What would need to happen for the goalposts to move again---or,
conversely, what evidence would suggest even to the sceptics that
general intelligence was within reach?

We ought to begin by saying what AI is; and straight away we run into
a problem. Presumably, one has artifical intelligence when a computer
(that's the “artifical” bit) exhibits intelligence (that's the
“intelligent” bit).  We know what computers are but what intelligence
is is much less clear.  I'm not a cognitive science researcher so take
the following with a grain of salt, but my sense is that there are
broadly three levels at which you might say what intelligence is.  At
an abstract, “you know it when you see it” level, one might say that
something is intelligent if it acts, in a variety of different
environments, in such a way as to achieve its goals.[fn:: /cf./ Legg
and Hutter, /Universal intelligence: a definition of machine
intelligence/ (2007).] This seems basically right to me.  AI is making
computers do something that, if you saw a person doing it, you'd say,
“huh, that looks smart.” At a slightly more concrete level, if you
were interested in figuring out how something could be intelligent,
you might say what kinds of /capability/ one needs to be intelligence.
For example, Wikipedia lists these[fn::
[[https://en.wikipedia.org/wiki/Artificial_intelligence]]] as: “learning,
reasoning, problem-solving, perception, and decision-making.”  

Turing, famously, took a third approach.  In 1950, in an article in
/Mind/, Turing proposed to reframe the entire question around an
adversarial contest. The idea of the contest was, “can a machine fool
a person into thinking that it, the machine, is also a person?”  The
great advantage of Turing's version was that the answer it gives is
clear and measurable.  One does not have to say whether the machine
has “met its goals,” or even what “goals” are.  One just has to run
the experiment.  Of course, for a long time building a machine that
could succeed at any reasonable version of Turing's game was
completely out of reach and so various alternative, more restrictive,
versions were proposed; for example, “can a machine beat a human at
chess?”

In my imagination, the history of AI research is a somewhat testy
dialogue between researchers and skeptics.  The researchers will say,
we believe that intelligence involves reasoning, and we have developed
a theory of what it is to reason.  And the skeptics say, that's all
fine and good, but can it beat me at chess?  So the researchers build
a machine that can beat the skeptic at chess.  And the skeptics say,
well, okay, but I see how you did that: you did a breadth-first tree
search with alpha-beta pruning (or whatever) and that's just a trick.
That's not real intelligence, that's just brute computational power:
where's the perception, or the learning?  Also, maybe chess is not as
hard as we thought.  I bet you can't, we don't know, [[https://xkcd.com/1425/][determine whether
a photograph contains a bird]]?

And so the researchers go off, muttering, and ten years later they
come back all tired and grimy from the connectionism mines with a
machine that can tell whether a photograph contains a bird.  And the
sceptics say, fine that is actually useful but still, most of the hard
work was taking about 10,000 photographs and spending weeks manually
classifying them into “bird” and “not-bird,” and then compressing them
down with, admittedly, a clever choice of compression.  It's not
really intelligence, it's mostly a trick.

To which the researchers say exasperatedly, come on, we've done
reasoning, we've done perception, we've sort of done learning if you
squint a little.  What more do you want?  And the sceptics say, what
about C-3PO?


 




